AutoCleanup: true
AutoPatching: true
ConfigurationFile: .github\auto-release.yml
CreateMajorTag: true
CreateMinorTag: true
DatePrereleaseFormat: ''
IgnoreLabels: NoRelease
IncrementalPrerelease: true
MajorLabels: major, breaking
MinorLabels: minor, feature, improvement
PatchLabels: patch, fix, bug
VersionPrefix: v
WhatIf: false
