name: Auto-Release (by PSModule)
description: Automatically creates releases based on pull requests and labels.
author: PSModule
branding:
  icon: activity
  color: blue

inputs:
  ConfigurationFile:
    description: The path to the configuration file.
    required: false
    default: '.github\auto-release.yml'

runs:
  using: composite
  steps:
    - name: Auto-Release
      shell: pwsh
      env:
        ConfigurationFile: ${{ inputs.ConfigurationFile }}
      run: . "$env:GITHUB_ACTION_PATH\scripts\main.ps1"
