name: Auto Release (by PSModule)
description: Automatically creates releases based on pull requests and labels.
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  AutoCleanup:
    description: Control wether to automatically delete the prerelease tags after the stable release is created.
    required: false
    default: 'true'
  AutoPatching:
    description: Control wether to automatically handle patches. If disabled, the action will only create a patch release if the pull request has a 'patch' label.
    required: false
    default: 'true'
  ConfigurationFile:
    description: The path to the configuration file. Settings in the configuration file take precedence over the action inputs.
    required: false
    default: .github\auto-release.yml
  CreateMajorTag:
    description: Control wether to create a major tag when a pull request is merged into the main branch.
    required: false
    default: 'true'
  CreateMinorTag:
    description: Control wether to create a minor tag when a pull request is merged into the main branch.
    required: false
    default: 'true'
  DatePrereleaseFormat:
    description: If specified, uses a date based prerelease scheme. The format should be a valid .NET format string like 'yyyyMMddHHmm'.
    required: false
    default: ''
  IgnoreLabels:
    description: A comma separated list of labels that do not trigger a release.
    required: false
    default: NoRelease
  IncrementalPrerelease:
    description: Control wether to automatically increment the prerelease number. If disabled, the action will ensure only one prerelease exists for a given branch.
    required: false
    default: 'true'
  MajorLabels:
    description: A comma separated list of labels that trigger a major release.
    required: false
    default: major, breaking
  MinorLabels:
    description: A comma separated list of labels that trigger a minor release.
    required: false
    default: minor, feature
  PatchLabels:
    description: A comma separated list of labels that trigger a patch release.
    required: false
    default: patch, fix
  UsePRTitleAsReleaseName:
    description: When enabled, uses the pull request title as the name for the GitHub release.
    required: false
    default: 'false'
  UsePRBodyAsReleaseNotes:
    description: When enabled, uses the pull request body as the release notes for the GitHub release.
    required: false
    default: 'true'
  UsePRTitleAsNotesHeading:
    description: When enabled, the release notes will begin with the pull request title as an H2 heading followed by the pull request body.
    required: false
    default: 'true'
  VersionPrefix:
    description: The prefix to use for the version number.
    required: false
    default: v
  WhatIf:
    description: If specified, the action will only log the changes it would make, but will not actually create or delete any releases or tags.
    required: false
    default: 'false'
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Auto-Release
      uses: PSModule/GitHub-Script@v1
      env:
        PSMODULE_AUTO_RELEASE_INPUT_AutoCleanup: ${{ inputs.AutoCleanup }}
        PSMODULE_AUTO_RELEASE_INPUT_AutoPatching: ${{ inputs.AutoPatching }}
        PSMODULE_AUTO_RELEASE_INPUT_ConfigurationFile: ${{ inputs.ConfigurationFile }}
        PSMODULE_AUTO_RELEASE_INPUT_CreateMajorTag: ${{ inputs.CreateMajorTag }}
        PSMODULE_AUTO_RELEASE_INPUT_CreateMinorTag: ${{ inputs.CreateMinorTag }}
        PSMODULE_AUTO_RELEASE_INPUT_DatePrereleaseFormat: ${{ inputs.DatePrereleaseFormat }}
        PSMODULE_AUTO_RELEASE_INPUT_IgnoreLabels: ${{ inputs.IgnoreLabels }}
        PSMODULE_AUTO_RELEASE_INPUT_IncrementalPrerelease: ${{ inputs.IncrementalPrerelease }}
        PSMODULE_AUTO_RELEASE_INPUT_MajorLabels: ${{ inputs.MajorLabels }}
        PSMODULE_AUTO_RELEASE_INPUT_MinorLabels: ${{ inputs.MinorLabels }}
        PSMODULE_AUTO_RELEASE_INPUT_PatchLabels: ${{ inputs.PatchLabels }}
        PSMODULE_AUTO_RELEASE_INPUT_UsePRBodyAsReleaseNotes: ${{ inputs.UsePRBodyAsReleaseNotes }}
        PSMODULE_AUTO_RELEASE_INPUT_UsePRTitleAsReleaseName: ${{ inputs.UsePRTitleAsReleaseName }}
        PSMODULE_AUTO_RELEASE_INPUT_UsePRTitleAsNotesHeading: ${{ inputs.UsePRTitleAsNotesHeading }}
        PSMODULE_AUTO_RELEASE_INPUT_VersionPrefix: ${{ inputs.VersionPrefix }}
        PSMODULE_AUTO_RELEASE_INPUT_WhatIf: ${{ inputs.WhatIf }}
      with:
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        WorkingDirectory: ${{ inputs.WorkingDirectory }}
        Script: |
          # Auto-Release
          ${{ github.action_path }}/scripts/main.ps1
