name: Auto-Release (by PSModule)
description: Automatically creates releases based on pull requests and labels.

branding:
  icon: activity
  color: blue

inputs:
  AutoPatching:
    description: Control wether to automatically handle patches. If disabled, the action will only create a patch release if the pull request has a 'patch' label.
    required: false
    default: 'true'
  IncrementalPrerelease:
    description: Control wether to automatically increment the prerelease number. If disabled, the action will ensure only one prerelease exists for a given branch.
    required: false
    default: 'true'
  DatePrereleaseFormat:
    description: If specified, uses a date based prerelease scheme. The format should be a valid .NET format string like 'yyyyMMddHHmm'.
    required: false
    default: ''
  VersionPrefix:
    description: The prefix to use for the version number.
    required: false
    default: 'v'

runs:
  using: composite
  steps:
    - name: Auto-Release
      shell: pwsh
      env:
        AutoPatching: ${{ inputs.AutoPatching }}
        IncrementalPrerelease: ${{ inputs.IncrementalPrerelease }}
        VersionPrefix: ${{ inputs.VersionPrefix }}
        DatePrereleaseFormat: ${{ inputs.DatePrereleaseFormat }}
      run: ./scripts/main.ps1
