name: Action-Test

on:
  pull_request:

jobs:
  ActionTestDefault:
    name: Action-Test - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          WhatIf: true
