name: Action-Test

on:
  push:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**
  pull_request:
    branches-ignore:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**

permissions:
  contents: read

jobs:
  ActionTestDefault:
    name: Action-Test - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          WhatIf: true
