name: Auto-Release

run-name: Auto-Release - [${{ github.event.pull_request.title }} \#${{ github.event.pull_request.number }}] by @${{ github.actor }}

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - labeled

concurrency:
  group: ${{ github.workflow }}

jobs:
  Auto-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Auto-Release
        uses: ./
        env:
          GH_TOKEN: ${{ github.token }} # Used for GitHub CLI authentication
